README.org --- description



Copyright (C) 2012 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of H-bridge.

  H-bridge is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  H-bridge is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with H-bridge.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
half full triple H-bridge

* Description:
schematic for: Half-H-bridge, (Full) H-bridge, Triple Half-H-bridge

* Usage:

* History:
Version 0.1 was created at 2010.sep.01

* Dependences:

* Comment

based on my project motorrka 
thanks to atom1477 form http://www.elektroda.pl/rtvforum/topic1841543.html
and http://cxem.net/beginner/beginner65.php
and http://cxem.net/pitanie/5-110.php (read last message with fix error)
and http://pro-radio.ru/power/7736/
and http://forum.cxem.net/index.php?showtopic=120700
